### ISSUE TITLE
Error with value <b64enc>

### ISSUE THREAD

**Issue by yulibe** [vbouchaud/chartrepo#1]
When I installed your repository I got this error : 
Error: INSTALLATION FAILED: template: k8s-ldap-auth/templates/ldap-config.yaml:9:48: executing "k8s-ldap-auth/templates/ldap-config.yaml" at <b64enc>: invalid value; expected string 

Then i found this solution : https://stackoverflow.com/questions/53704760/kubernetes-putting-json-value-in-yaml-file 

Can you check if the problem is on your part (if you have the same problem than me).

Thank you.

**Comment by vbouchaud** [comment]
Hi @yulibe,

Granted I should have wrote it in the documentation, when using k8s-ldap-auth chart the operator has to fill `config.keys.privateKeyData` and `config.keys.privateKeyData`: those fields are mandatory. This is needed for JWT token signing and validation.

Those field have a default value that will fail the deployment on purpose if not replaced : you should indeed provide base64 encoded values there.

Let me know if i can be of further assistance.
